### ISSUE TITLE
Issue with jumper 6s pro

### ISSUE THREAD

**Issue by fantommohammed** [BlissRoms-x86/manifest#26]
Hello i have try to install android kernel 4.9 ;4.19;4.20. But all i have the same problem the wifi  not working and giving me error mac address not available

My pc is jumper 6s pro

**Comment by electrikjesus** [comment]
Please use our Telegram chat (t.me/blissx86) or our XDA thread to post what wireless chipset you have along with any other info on the components in that device. That way we can see if we can add what's missing.
