### ISSUE TITLE
Error when build Bliss OS Android Q with gapps

### ISSUE THREAD

**Issue by imaandrew** [BlissRoms-x86/manifest#27]
When I try to build Bliss OS from the android q branch with gapps, I get the error:

```
FAILED:
vendor/bliss/prebuilt/common/Android.mk: error: ActionsServices: No source files specified
build/make/core/prebuilt_internal.mk:37: error: done.
```
I have synced the opengapps vendor files

**Comment by electrikjesus** [comment]
That's an odd one. I'm in the middle of redoing our vendor anyways for Bliss OS, so I'll take a look into it later on this weekend

**Comment by electrikjesus** [comment]
Can you share the manifest for the opengapps sources you synced?

**Comment by imaandrew** [comment]
I added the manifest from step 1 into my default manifest file

https://github.com/opengapps/aosp_build

**Comment by imaandrew** [comment]
Just so you know, this is also happening on the q-x86-12.1 branch
