### ISSUE TITLE
BD PROCHOT cpu throttling (msr read and write)

### ISSUE THREAD

**Issue by imad07mos** [BlissRoms-x86/manifest#32]
Hello , lot of intel laptops suffers from BD PROCHOT flag that throttles cpu when charging , its easily fixable in windows using throttlestop and linux using msr tools

me and my friend tried to port msr tools to android x86 and compiled it using ndk in Android 7.x source

copied binary files and chmoded them then modprobe msr

rdmsr 0x1FC

it returns this error "rdmsr: open : no such file or directory"

here is the source code of what my friend compiled

https://github.com/hmtheboy154/msr-tools-android

reference :

https://github.com/DivyanshuVerma/throttlestop-linux

**Comment by ericswpark** [comment]
Sorry, but this is not the correct place to file bug reports. Please file all Bliss OS related bugs here: https://github.com/BlissRoms-x86/bug_reports

**Comment by ericswpark** [comment]
The issue was not transferred because the repository linked above has the correct issue template. Please use the template to submit your bug report. Thank you!
