### ISSUE TITLE
Error building Bliss os 11.x

### ISSUE THREAD

**Issue by purplepalmdash** [BlissRoms-x86/manifest#40]
Follow the build guide of `https://docs.blissos.org/development/build-bliss-os-11.x` I met this issue:    

```
Checking ChromeOS image...
chromeos_13421.73.0_nocturne_recovery_stable-channel_mp.bin.zip: OK
 -> Extracting recovery image
 -> Mounting partitions
 -> Deleting old files
 -> Copying files
Done
Building proprietary tools, part 2... Gearlock Recovery Patches...
This won't take too long...

build-x86.sh: line 346: apply-gearlock-patches: command not found
```
Then I use the `Advanced build instructions`,  which failed at `mka update_engine_applier`

```
# . build/envsetup.sh && lunch android_x86_64-userdebug && mka update_engine_applier

1/1] /media/sdb1/p9.0/out/soong/.bootstrap/b..._build /media/sdb1/p9.0/out/soong/build.ninja
FAILED: /media/sdb1/p9.0/out/soong/build.ninja 
/media/sdb1/p9.0/out/soong/.bootstrap/bin/soong_build -t -l /media/sdb1/p9.0/out/.module_paths/Android.bp.list -b /media/sdb1/p9.0/out/soong -n /media/sdb1/p9.0/out -d /media/sdb1/p9.0/out/soong/build.ninja.d -o /media/sdb1/p9.0/out/soong/build.ninja Android.bp
error: external/bison/Android.bp:43:14: unrecognized property "target.glibc"
error: external/bison/Android.bp:49:13: unrecognized property "target.musl"
error: external/bison/linux_glibc-lib/Android.bp:6:14: unrecognized property "target.glibc"
error: external/bison/linux_musl-lib/Android.bp:6:13: unrecognized property "target.musl"
error: external/bison/linux_glibc-lib/Android.bp:103:14: unrecognized property "target.glibc"
error: external/bison/linux_musl-lib/Android.bp:110:13: unrecognized property "target.musl"
ninja: build stopped: subcommand failed.
16:27:03 soong bootstrap failed with: exit status 1

#### failed to build some targets (1 seconds) ####
```

could you please help solving this building problem? thanks.

**Comment by hmtheboy154** [comment]
go to external/bison and revert commit ```f2eb9d330b112b0d6f871fd7473ca3c1624702b6```, it will work

**Comment by zsmweb** [comment]
but the commit f2eb9d330b112b0d6f871fd7473ca3c1624702b6 is not exist.

**Comment by utzcoz** [comment]
Android-x86 Google groups has a similar problem. You can check it.

**Comment by hmtheboy154** [comment]
I think I accidentally copy my revert commit code.......... but here's the one you need to revert 
https://android.googlesource.com/platform/external/bison/+/54f151ae693a518cb977481d635c1b51aa93a0a5

**Comment by mscottwvc** [comment]
So this fix never got pushed?

**Comment by mscottwvc** [comment]
If I revert I end up with this error:
`[1050/1081] including vendor/fdroid/FDroidPrivilegedExtension/Android.mk ...
build/make/core/base_rules.mk:260: error: vendor/fdroid/FDroidPrivilegedExtension: MODULE.TARGET.APPS.FDroidPrivilegedExtension already defined by packages/apps/FDroidPrivilegedExtension/app/src/main.
15:58:56 ckati failed with: exit status 1
`

**Comment by hmtheboy154** [comment]
remove vendor/fdroid

**Comment by hmtheboy154** [comment]
or you can try this repo
https://github.com/supremegamers/android/tree/bliss/pie-x86

**Comment by mscottwvc** [comment]
> or you can try this repo https://github.com/supremegamers/android/tree/bliss/pie-x86

Thanks, I tried that repo this morning but got this error in the build:
`============================================
BLISS_VERSION=Bliss-v11.20--UNOFFICIAL-20221108
TARGET_PRODUCT=android_x86_64
TARGET_BUILD_VARIANT=userdebug
TARGET_ARCH=x86_64
TARGET_ARCH_VARIANT=x86_64
BUILD_ID=PQ2A.190405.003
============================================
ninja: no work to do.
[1/1] /home/mscott/bliss/supreme/out/soong/.bootstrap/bin/...ong_build /home/mscott/bliss/supreme/out/soong/build.ninja
FAILED: /home/mscott/bliss/supreme/out/soong/build.ninja 
/home/mscott/bliss/supreme/out/soong/.bootstrap/bin/soong_build -t -l /home/mscott/bliss/supreme/out/.module_paths/Android.bp.list -b /home/mscott/bliss/supreme/out/soong -n /home/mscott/bliss/supreme/out -d /home/mscott/bliss/supreme/out/soong/build.ninja.d -o /home/mscott/bliss/supreme/out/soong/build.ninja Android.bp
error: external/minigbm/Android.bp:151:19: unrecognized property "apex_available"
error: external/libdrm/Android.bp:63:23: unrecognized property "recovery_available"
error: external/libdrm/data/Android.bp:1:1: unrecognized module type "prebuilt_etc"
error: external/minigbm/gbm_mesa_driver/Android.bp:39:20: unrecognized property "vintf_fragments"
error: external/minigbm/cros_gralloc/gralloc4/Android.bp:61:20: unrecognized property "vintf_fragments"
error: external/minigbm/cros_gralloc/gralloc4/Android.bp:69:20: unrecognized property "vintf_fragments"
error: external/minigbm/gbm_mesa_driver/Android.bp:47:20: unrecognized property "vintf_fragments"
error: external/minigbm/cros_gralloc/gralloc4/Android.bp:77:20: unrecognized property "vintf_fragments"
error: external/minigbm/cros_gralloc/gralloc4/Android.bp:85:20: unrecognized property "vintf_fragments"
error: external/minigbm/cros_gralloc/gralloc4/Android.bp:102:20: unrecognized property "vintf_fragments"
error: external/minigbm/cros_gralloc/gralloc4/Android.bp:110:20: unrecognized property "vintf_fragments"
error: external/minigbm/cros_gralloc/gralloc4/Android.bp:118:20: unrecognized property "vintf_fragments"
error: external/minigbm/cros_gralloc/gralloc4/Android.bp:126:20: unrecognized property "vintf_fragments"
`

**Comment by hmtheboy154** [comment]
oh right, all of the graphics stacks are now updated for Android 11 and above I forgot. 
Currently I don't have time and plan for BlissOS 11 (Android 9) now as I am busy with higher version, but if you really want to compile you should start looking for repo from maurossi, youling257 or SupremeGamers for reference
https://github.com/youling257
https://github.com/maurossi
https://github.com/supremegamers

**Comment by jsommr** [comment]
Reverting to https://android.googlesource.com/platform/external/bison/+/133f07eb33b32727e058dd25a1441ab4c2fc127a makes the error go away

```bash
cd external/bison
git reset --hard 133f07eb33b32727e058dd25a1441ab4c2fc127a
```

**Comment by zmuxuny** [comment]
Did the issue reporter resolve the problem? I always encounter this issue when I'm building the ISO with `mka iso`:

```
ninja: error: '/home/asdf/blissos/p9.0/out/target/product/x86_64/obj_x86/SHARED_LIBRARIES/libLLVM12_intermediates/export_includes', needed by '/home/asdf/blissos/p9.0/out/target/product/x86_64/obj_x86/SHARED_LIBRARIES/gallium_dri_intermediates/import_includes', missing and no known rule to make it
```
