### ISSUE TITLE
It worked very well but...

### ISSUE THREAD

**Issue by net-warriors** [BlissRoms-x86/manifest#46]
we downloaded the foss version from the link below and installed it in virtualbox
https://yer.dl.sourceforge.net/project/blissos-x86/Official/bleeding_edge/Generic%20builds%20-%20Pie/11.14/Bliss-v11.14--OFFICIAL-20210508-1013_x86_64_k-k4.19.122-ax86-ga-rmi_m-20.1.10_pie-x86_dgc-p9.0-11.13_ld-p9.0-x86_dg-_dh-blueprint_pie-x86_w45_2020_mg-p9.0-x86.iso
It worked very well, but its volume is much more than what can be used quickly and smoothly, please make it suitable for virtual machines.
 Thank you very much for your efforts, this is what we have been looking for for a long time.  We are in Iran and unfortunately we cannot support you financially, otherwise we would have supported you, thank you for your efforts

**Comment by hmtheboy154** [comment]
>  but its volume is much more than what can be used quickly and smoothly, please make it suitable for virtual machines.


i don't know what are you trying to say ?
