### ISSUE TITLE
How to use USB serial port debugging?

### ISSUE THREAD

**Issue by ldwdnmd** [BlissRoms-x86/manifest#51]
Hi

I encounter some serious kernel errors, and I need to use the USB serial port to get a log. I tried to add Console = ttyUSB0,115200 to CMDLINE and start it. It only shows the black screen, and the system cannot start.

CONFIG_USB_SERIAL=y
CONFIG_USB_SERIAL_CONSOLE=y
CONFIG_USB_SERIAL_CH341=y

**Comment by Xtr126** [comment]
The following system file modification can be used to enable the serial console in Bliss OS 14.10 / 15.8 builds. It will give access to Android shell. 
Edit /system/etc/init/hw/init.rc and change
```
line 1281:on init && property:ro.debuggable=1 && property:ro.console.enable=1
line 1282:    start console
```
to
```
on init
  start console 
```

**Comment by ldwdnmd** [comment]
> 
Thanks!
