### ISSUE TITLE
Can't install any android-x86 based system on Intel Gen 13, Kernel version 6

### ISSUE THREAD

**Issue by Josky-olo** [BlissRoms-x86/manifest#54]
Can you please update it to support it?

**Comment by electrikjesus** [comment]
This issue has already been reported and multiple solutions are in the process of being merged. Thank you for your patience.

**Comment by Josky-olo** [comment]
Thank you for your reply. Thank you for your best support.

**Comment by hmtheboy154** [comment]
https://mega.nz/file/j1xiwCJQ#hLCeCbMuRdqKMY8HycrZLxE1kaO3HSAT_TzkHEppcAg

**Comment by Josky-olo** [comment]
> https://mega.nz/file/j1xiwCJQ#hLCeCbMuRdqKMY8HycrZLxE1kaO3HSAT_TzkHEppcAg

Thank you very much, I will try it out.

**Comment by Florisv1** [comment]
There's no version of this build yet with Gapps support right? (We will have to wait for that.)

**Comment by Josky-olo** [comment]
> There's no version of this build yet with Gapps support right? (We will have to wait for that.)

Please check out this link: [(https://blissos.org/index.html#download)]

**Comment by Florisv1** [comment]
Thanks, I will check that out and try what works/what doesn't

19 jan. 2024 08:35:32 _Josky ***@***.***>:

**Comment by hmtheboy154** [comment]
There's BlissOS Zenith now
