### ISSUE TITLE
scm.osdn.net has been down for almost 2 months

### ISSUE THREAD

**Issue by jake5253** [BlissRoms-x86/manifest#55]
Attempts to access scm.osdn.net yields a warning page on Chrome:
```
This server could not prove that it is scm.osdn.net; its security certificate expired 54 days ago.
```
Continuing anyways gives a 404.

Repo sync fails.

A workaround is to edit your source's .repo/manifests/android-x86/00-remotes.xml
change `  <remote name="x86" fetch="https://scm.osdn.net/gitroot/android-x86" />`
to: `  <remote name="x86" fetch="git://git.osdn.net/gitroot/android-x86" />`

I know nothing additional about the situation, but it seems that letting it go for 2 months now kind of tells me that the website, as a whole(?) is.. eh.. not healthy. Anyone have backups?

**Comment by electrikjesus** [comment]
I'll push the remaining repos to github.com/Android-x86-mirror this weekend

**Comment by hmtheboy154** [comment]
we actually use none of the projects on Android-x86 nowadays, all projects are now moved to here on BlissRoms-x86 or Android-Generic github

So we can even remove the remote if you want

**Comment by hmtheboy154** [comment]
Now none of our manifest is tracking Android-x86 one
