### ISSUE TITLE
BlissOS 15.x Build Error

### ISSUE THREAD

**Issue by natsumerinchan** [BlissRoms-x86/manifest#56]
OS: ArchLinux
RAM:16GB
Branch:arcadia-x86

Error log:
```
FAILED: /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/.timestamp
/bin/bash -c "(cp /home/celica/workdir/Android-x86/glodroid/aospext/tools/wrapper.sh /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/toolchain_wrapper/wrapper.sh ) && (ln -sf ./wrapper.sh /home/celica/workdir/
Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/toolchain_wrapper/wrap_c ) && (ln -sf ./wrapper.sh /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/toolchain_wrapper/wrap_cxx ) && (ln -sf ./wrapper.sh /
home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/toolchain_wrapper/wrap_rust_ld ) && (cp /home/celica/workdir/Android-x86/glodroid/aospext/tools/gen_aospless_dir.py /home/celica/workdir/Android-x86/out/target/pr
oduct/x86_64/obj/AOSPEXT/DAV1D/gen_aospless_dir.py ) && (cp /home/celica/workdir/Android-x86/glodroid/aospext/tools/makefile_base.mk /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/Makefile ) && (cp /home/celi
ca/workdir/Android-x86/glodroid/aospext/tools/makefile_meson.mk /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/project_specific.mk ) && (sed -i 		-e 's#\\[PLACE_FOR_LLVM_DIR\\]#prebuilts/clang/host/li
nux-x86/clang-r416183b1/bin#g' 		-e 's#\\[PLACE_FOR_AOSP_ROOT\\]#/home/celica/workdir/Android-x86#g' 		-e 's#\\[PLACE_FOR_AOSP_OUT_DIR\\]#/home/celica/workdir/Android-x86/out#g' 		-e 's#\\[PLACE_FOR_SRC_DIR\\]#
glodroid/dav1d#g' 		-e 's#\\[PLACE_FOR_PATCHES_DIRS\\]##g' 		-e 's#\\[PLACE_FOR_OUT_BASE_DIR\\]#/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D#g' 		/home/celica/workdir/Android-x
86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/Makefile ) && (mkdir -p /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/gen ) && (sed -i 		-e 's#\\[PLACE_FOR_MESON_DEFS\\]#--prefix /vendor --libdir lib
64 --datadir etc/shared --libexecdir bin --sbindir bin --localstatedir=/mnt/var --buildtype=debug #g' 		/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/project_specific.mk ) && (cp /home/celica/workdir
/Android-x86/glodroid/aospext/tools/meson_aosp_cross.cfg /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/gen/meson_aosp_cross ) && (sed -i 		-e 's#\$(AR_TOOL)#prebuilts/clang/host/linux-x86/clang
-r416183b1/bin/llvm-ar#g' 		-e 's#\$(MESON_CPU_FAMILY)#x86_64#g' 		-e 's#\$(MESON_RUST_TARGET)#x86_64-linux-android#g' 		/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/gen/meson
_aosp_cross ) && (sed -i 		-e 's#\\[PLACE_FOR_RUST_TARGET\\]#x86_64-linux-android#g' 		/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/project_specific.mk ) && (sed -i 		-e 's#
\\[PLACE_FOR_FFMPEG_DEFINITIONS\\]#--libdir=/vendor/lib64 #g' 		-e 's#\\[PLACE_FOR_FFMPEG_CPU_FAMILY\\]#x86_64#g' 		/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/project_specific.mk ) && 
(export \$(cat /etc/environment):/home/celica/.cargo/bin:/home/celica/workdir/Android-x86/prebuilts/clang/host/linux-x86/clang-r416183b1/bin && make -C /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D install )
 && (touch /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/.timestamp )"
"make" is not allowed to be used. See https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools for more information.
18:00:47 ninja failed with: exit status 1
```

I was able to compile it successfully last week.

**Comment by electrikjesus** [comment]
That's a new one for me. Try adding 'make' command to the config.go here: https://github.com/BlissRoms-x86/platform_build_soong/blob/3ecac47fe1e39fe5d384f217260b31b6ffdf6e87/ui/build/paths/config.go#L99

**Comment by natsumerinchan** [comment]
> That's a new one for me. Try adding 'make' command to the config.go here: https://github.com/BlissRoms-x86/platform_build_soong/blob/3ecac47fe1e39fe5d384f217260b31b6ffdf6e87/ui/build/paths/config.go#L99这对我来说是一个新问题。尝试在此处将“make”命令添加到config.go中： https://github.com/BlissRoms-x86/platform_build_soong/blob/3ecac47fe1e39fe5d384f217260b31b6ffdf6e87/ui/build/paths/config.go#L99

Thanks.I will try it tomorrow,now I am building `r11-x86`.(It will take me about 6 hours.)

**Comment by electrikjesus** [comment]
Another thought is to make sure you have that dav1d repo checked out at the v1.3.0 tag and not main

**Comment by hmtheboy154** [comment]
> Another thought is to make sure you have that dav1d repo checked out at the v1.3.0 tag and not main

I use revision now

**Comment by hmtheboy154** [comment]
> OS: ArchLinux RAM:16GB Branch:arcadia-x86
> 
> Error log:
> 
> ```
> FAILED: /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/.timestamp
> /bin/bash -c "(cp /home/celica/workdir/Android-x86/glodroid/aospext/tools/wrapper.sh /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/toolchain_wrapper/wrapper.sh ) && (ln -sf ./wrapper.sh /home/celica/workdir/
> Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/toolchain_wrapper/wrap_c ) && (ln -sf ./wrapper.sh /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/toolchain_wrapper/wrap_cxx ) && (ln -sf ./wrapper.sh /
> home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/toolchain_wrapper/wrap_rust_ld ) && (cp /home/celica/workdir/Android-x86/glodroid/aospext/tools/gen_aospless_dir.py /home/celica/workdir/Android-x86/out/target/pr
> oduct/x86_64/obj/AOSPEXT/DAV1D/gen_aospless_dir.py ) && (cp /home/celica/workdir/Android-x86/glodroid/aospext/tools/makefile_base.mk /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/Makefile ) && (cp /home/celi
> ca/workdir/Android-x86/glodroid/aospext/tools/makefile_meson.mk /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/project_specific.mk ) && (sed -i 		-e 's#\\[PLACE_FOR_LLVM_DIR\\]#prebuilts/clang/host/li
> nux-x86/clang-r416183b1/bin#g' 		-e 's#\\[PLACE_FOR_AOSP_ROOT\\]#/home/celica/workdir/Android-x86#g' 		-e 's#\\[PLACE_FOR_AOSP_OUT_DIR\\]#/home/celica/workdir/Android-x86/out#g' 		-e 's#\\[PLACE_FOR_SRC_DIR\\]#
> glodroid/dav1d#g' 		-e 's#\\[PLACE_FOR_PATCHES_DIRS\\]##g' 		-e 's#\\[PLACE_FOR_OUT_BASE_DIR\\]#/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D#g' 		/home/celica/workdir/Android-x
> 86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/Makefile ) && (mkdir -p /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/gen ) && (sed -i 		-e 's#\\[PLACE_FOR_MESON_DEFS\\]#--prefix /vendor --libdir lib
> 64 --datadir etc/shared --libexecdir bin --sbindir bin --localstatedir=/mnt/var --buildtype=debug #g' 		/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/project_specific.mk ) && (cp /home/celica/workdir
> /Android-x86/glodroid/aospext/tools/meson_aosp_cross.cfg /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/gen/meson_aosp_cross ) && (sed -i 		-e 's#\$(AR_TOOL)#prebuilts/clang/host/linux-x86/clang
> -r416183b1/bin/llvm-ar#g' 		-e 's#\$(MESON_CPU_FAMILY)#x86_64#g' 		-e 's#\$(MESON_RUST_TARGET)#x86_64-linux-android#g' 		/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/gen/meson
> _aosp_cross ) && (sed -i 		-e 's#\\[PLACE_FOR_RUST_TARGET\\]#x86_64-linux-android#g' 		/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/project_specific.mk ) && (sed -i 		-e 's#
> \\[PLACE_FOR_FFMPEG_DEFINITIONS\\]#--libdir=/vendor/lib64 #g' 		-e 's#\\[PLACE_FOR_FFMPEG_CPU_FAMILY\\]#x86_64#g' 		/home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/project_specific.mk ) && 
> (export \$(cat /etc/environment):/home/celica/.cargo/bin:/home/celica/workdir/Android-x86/prebuilts/clang/host/linux-x86/clang-r416183b1/bin && make -C /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D install )
>  && (touch /home/celica/workdir/Android-x86/out/target/product/x86_64/obj/AOSPEXT/DAV1D/.timestamp )"
> "make" is not allowed to be used. See https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools for more information.
> 18:00:47 ninja failed with: exit status 1
> ```
> 
> I was able to compile it successfully last week.

is this the full log ? Can you upload the full part of it or `out/error.log` ? Idk why on Ubuntu we can build file and on Arch it was blocked like that

**Comment by rsglobal** [comment]
Hi guys,

Please try applying this patch and see if it fixes the issue:

```diff
diff --git a/aospext_cross_compile.mk b/aospext_cross_compile.mk
index 25acd29..176a61e 100644
--- a/aospext_cross_compile.mk
+++ b/aospext_cross_compile.mk
@@ -121,6 +121,6 @@ $(AOSPEXT_INTERNAL_BUILD_TARGET): $(AOSP_FLAGS_DIR_OUT)/.sharedlib.timestamp
                $(AOSPEXT_ABS_OUT_DIR)/project_specific.mk
 
        # Build project
-       export $$(cat /etc/environment):$(RUST_BIN_DIR_ABS):$(AOSP_ABSOLUTE_PATH)/$(LLVM_PREBUILTS_PATH) && make -C $(AOSPEXT_ABS_OUT_DIR) install
+       export PATH=$(RUST_BIN_DIR_ABS):$(AOSP_ABSOLUTE_PATH)/$(LLVM_PREBUILTS_PATH):$$(cat $(OUT_DIR)/.path_interposer_origpath) && make -C $(AOSPEXT_ABS_OUT_DIR) install
 
        touch $@
```

**Comment by hmtheboy154** [comment]
> Hi guys,
> 
> Please try applying this patch and see if it fixes the issue:
> 
> ```diff
> diff --git a/aospext_cross_compile.mk b/aospext_cross_compile.mk
> index 25acd29..176a61e 100644
> --- a/aospext_cross_compile.mk
> +++ b/aospext_cross_compile.mk
> @@ -121,6 +121,6 @@ $(AOSPEXT_INTERNAL_BUILD_TARGET): $(AOSP_FLAGS_DIR_OUT)/.sharedlib.timestamp
>                 $(AOSPEXT_ABS_OUT_DIR)/project_specific.mk
>  
>         # Build project
> -       export $$(cat /etc/environment):$(RUST_BIN_DIR_ABS):$(AOSP_ABSOLUTE_PATH)/$(LLVM_PREBUILTS_PATH) && make -C $(AOSPEXT_ABS_OUT_DIR) install
> +       export PATH=$(RUST_BIN_DIR_ABS):$(AOSP_ABSOLUTE_PATH)/$(LLVM_PREBUILTS_PATH):$$(cat $(OUT_DIR)/.path_interposer_origpath) && make -C $(AOSPEXT_ABS_OUT_DIR) install
>  
>         touch $@
> ```

@natsumerinchan apply patch to `glodroid/aospext`

**Comment by natsumerinchan** [comment]
Error solved. Thanks.
