### ISSUE TITLE
repo init -u https://github.com/BlissRoms-x86/manifest.git -b n7.1-x86 failed.

### ISSUE THREAD

**Issue by getfeus** [BlissRoms-x86/manifest#6]
Hello. 

I am trying to build blissRoms-x86.

`repo init  -u https://github.com/BlissRoms-x86/manifest.git -b n7.1-x86`
command failed with error message 
```
fatal: manifest 'default.xml' not available
fatal: duplicate path external/openssh in /mnt/sdb/src/BlissRoms/.repo/manifests/default.xml
```

How can I sync to your branch? 

Best regards.

**Comment by francisuk1989** [comment]
please try this again
